Jumanji/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from vacancies.views import DetailVacancyView, MainView, VacanciesByCompanyView, \
    VacanciesListView, VacanciesBySpecialityView, SendVacancyView, MycompanyCreate, CompanyLetsstart, \
    CompanyVacancies, CompanyVacanciesCreate, CompanyEdit, CompanyVacanciesEdit

from accounts.views import LogoutFormView, RegisterUserView, LoginUserView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name="main"),
    path('vacancies/', VacanciesListView.as_view(), name="all_vacancies"),
    path('vacancies/cat/<str:code>', VacanciesBySpecialityView.as_view(), name="speciality"),
    path('companies/<int:id>', VacanciesByCompanyView.as_view(), name="company"),
    path('vacancies/<int:pk>', DetailVacancyView.as_view(), name="single_vakancy"),

    path('vacancies/<int:pk>/send', SendVacancyView.as_view(), name="send"),
    path('mycompany/letsstart', CompanyLetsstart.as_view(), name="company_edit"),
    path('mycompany/create', MycompanyCreate.as_view(), name="company_create"),
    path('mycompany', CompanyEdit.as_view(), name="my_company"),
    path('mycompany/vacancies', CompanyVacancies.as_view(), name="company_vacancies"),
    path('mycompany/vacancies/create', CompanyVacanciesCreate.as_view(), name="create_vacancy"),
    path('mycompany/vacancies/<int:vacancy_id>', CompanyVacanciesEdit.as_view(), name="update_vacancy"),

    path('login', LoginUserView.as_view(), name="login"),
    path('register', RegisterUserView.as_view(), name="register"),
    path('logout', LogoutFormView.as_view(), name="logout"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

# handler404 = CustomHendler.custom_handler404
# handler500 = CustomHendler.custom_handler500

vacancies/models.py
from django.db import models
from django.contrib.auth.models import User


class Specialty(models.Model):
    code = models.CharField(max_length=20)
    title = models.CharField(max_length=20)
    picture = models.ImageField(upload_to="MEDIA_SPECIALITY_IMAGE_DIR")


class Company(models.Model):
    name = models.CharField(max_length=20)
    location = models.CharField(max_length=20)
    logo = models.ImageField(upload_to="MEDIA_COMPANY_IMAGE_DIR", null=True)
    description = models.TextField(max_length=100)
    employee_count = models.IntegerField()
    owner = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)


class Vacancy(models.Model):
    title = models.CharField(max_length=20)
    specialty = models.ForeignKey(Specialty, related_name="vacancies", on_delete=models.DO_NOTHING)
    company = models.ForeignKey(Company, related_name="vacancies", on_delete=models.DO_NOTHING)
    skills = models.CharField(max_length=50)
    description = models.TextField(max_length=100)
    salary_min = models.IntegerField()
    salary_max = models.IntegerField()
    published_at = models.DateField(auto_now_add=True)


class Application(models.Model):
    written_username = models.CharField(max_length=20)
    written_phone = models.IntegerField()
    written_cover_letter = models.TextField(max_length=200)
    vacancy = models.ForeignKey(Vacancy, related_name="applications", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="applications", on_delete=models.CASCADE)

vacancies/forms.py
from django import forms

from vacancies.models import User, Application, Company, Vacancy


class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password",)


class LoginUserForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password",)


class ApplicationForm(forms.ModelForm):

    class Meta:
        model = Application
        fields = ("written_username", "written_phone", "written_cover_letter",)


class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ("name", "location", "description", "employee_count")


class VacancyForm(forms.ModelForm):

    class Meta:
        model = Vacancy
        fields = ("title", "salary_min", "salary_max", "skills", "description", "specialty")

vacancies/views.py
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.core.exceptions import ObjectDoesNotExist


from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect, reverse

from django.views.generic import ListView, TemplateView, View, CreateView, DetailView, UpdateView

from vacancies.forms import ApplicationForm, CompanyForm, VacancyForm
from vacancies.models import Company, Specialty, Vacancy, Application


class MainView(TemplateView):
    template_name = "public/index.html"

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context["speciality_list"] = Specialty.objects.annotate(vacancy_count=Count("vacancies"))
        context["company_list"] = Company.objects.annotate(vacancy_count=Count("vacancies"))
        return context


class VacanciesListView(ListView):
    model = Vacancy
    template_name = "public/vacancies.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(VacanciesListView, self).get_context_data(**kwargs)
        count_vacan = Vacancy.objects.aggregate(vacancy_count=Count("id"))
        context["count_vacancy"] = count_vacan["vacancy_count"]
        return context


class VacanciesBySpecialityView(ListView):
    template_name = "public/vacancies.html"

    def get_queryset(self):
        self.speciality = get_object_or_404(Specialty, code=self.kwargs["code"])
        self.queryset = self.speciality.vacancies.all()
        return super(VacanciesBySpecialityView, self).get_queryset()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["speciality_title"] = self.speciality.title
        context["speciality_id"] = self.speciality.id
        spec_count = Specialty.objects.annotate(vacancy_count=Count("vacancies"))
        for count in spec_count:
            if self.speciality.id == count.id:
                context["count_vacancy"] = count.vacancy_count
        return context


class VacanciesByCompanyView(ListView):
    template_name = "public/company.html"

    def get_queryset(self):
        self.company = get_object_or_404(Company, pk=self.kwargs["id"])
        self.queryset = self.company.vacancies.all()
        return super(VacanciesByCompanyView, self).get_queryset()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["company_name"] = self.company.name
        context["company_location"] = self.company.location
        context["company_id"] = self.company.id
        context["count_in_company"] = Company.objects.annotate(vacancy_count=Count("vacancies"))
        context["company_logo"] = self.company.logo
        return context


class DetailVacancyView(DetailView):
    model = Vacancy
    template_name = "vacancies/vacancy.html"
    form_class = ApplicationForm

    def get_context_data(self, form=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = form or self.form_class()
        return context

    def post(self, request, pk):
        form = self.form_class(request.POST)
        if form.is_valid():
            aplication = form.save(commit=False)
            aplication.user = request.user
            aplication.vacancy_id = pk
            aplication.save()
            return redirect("send", pk)
        self.object = self.get_object()
        return self.render_to_response(self.get_context_data(form=form))


class SendVacancyView(View):
    template_name = "vacancies/send.html"

    def get(self, request, pk):
        return render(request, "vacancies/send.html")


class MycompanyCreate(LoginRequiredMixin, CreateView):
    template_name = 'company/company-edit.html'
    form_class = CompanyForm

    def get(self, request, *args, **kwargs):
        try:
            Company.objects.get(owner_id=request.user.id)
            return redirect('company_edit')
        except ObjectDoesNotExist:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class CompanyEdit(LoginRequiredMixin, UpdateView):
    template_name = 'company/company-edit.html'
    form_class = CompanyForm

    def get(self, request, *args, **kwargs):
        try:
            Company.objects.get(owner_id=request.user.id)
        except ObjectDoesNotExist:
            return redirect('company_edit')
        return super().get(request, *args, **kwargs)

    def get_object(self, **kwargs):
        company = Company.objects.get(owner_id=self.request.user.id)
        return company

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class CompanyLetsstart(LoginRequiredMixin, TemplateView):
    template_name = 'company/company-create.html'



class CompanyVacancies(LoginRequiredMixin, ListView):
    model = Vacancy
    template_name = 'vacancies/vacancy-list.html'

    def get(self, request, *args, **kwargs):
        try:
            Company.objects.get(owner_id=request.user.id)
        except ObjectDoesNotExist:
            return redirect('company_edit')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vacancy'] = Vacancy.objects.filter(company__owner=self.request.user.id)
        return context


class CompanyVacanciesCreate(LoginRequiredMixin, CreateView):
    template_name = 'vacancies/vacancy-edit.html'
    form_class = VacancyForm

    def form_valid(self, form):
        form.instance.company = Company.objects.get(owner_id=self.request.user.id)
        return super().form_valid(form)


class CompanyVacanciesEdit(LoginRequiredMixin, UpdateView):
    template_name = 'vacancies/vacancy-edit.html'
    form_class = VacancyForm
    success_url = 'company_edit'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['application'] = Application.objects.filter(
            vacancy__id=self.kwargs['vacancy_id']).annotate(count=Count('id'))
        return context

    def get_object(self, **kwargs):
        try:
            vacancy = Vacancy.objects.filter(company__owner=self.request.user).get(id=self.kwargs['vacancy_id'])
        except ObjectDoesNotExist:
            raise Http404
        return vacancy

vacancies/templates/vacancies/send.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Отклик отправлен | Джуманджи</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

{% extends "public/base.html" %}

{% block content %}
  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-10 col-md-6 offset-1 offset-md-3 mt-5">
        <div class="card mb-3">
          <div class="card-body text-center pt-5">
            <img src="#" width="65" alt="">
            <h2 class="h5 card-title mt-4 mb-2">Отклик отправлен</h2>
            <input type="button" onclick="history.back()" value="Вернуться к вакансии"/>
          </div>
        </div>
      </div>
    </div>
  </main>
  {% endblock content %}

vacancies/templates/vacancies/vacancy-edit.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Вакансии компании | Джуманджи</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    body {
      background-color: #F6F2E6;
    }
  </style>
</head>
{% extends "public/base.html" %}

{% block content %}
<form method="post">
{% csrf_token %}
  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills">
            <a class="nav-link" href="{% url "company_create" %}">1. Информация о&nbsp;компании</a>
            <a class="nav-link active" href="{% url "company_vacancies" %}">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4 tab-content">
            <!-- Tab -->
            <form>
              <h2 class="h4 pt-2 pb-3">Backend Middle/Senior</h2>
{#              <p class="alert alert-info" role="alert">Вакансия обновлена</p>#}
              <form action="/echo" enctype="multipart/form-data">
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      <label class="mb-2 text-dark" for="vacancyTitle">Название вакансии</label>
                      <input class="form-control" type="text" value="{{ vacancy.title }}" name="title" id="vacancyTitle">
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      <label class="mb-2 text-dark" for="userSpecialization">Специализация</label>
                      <select class="custom-select mr-sm-2" name="specialty" id="userSpecialization">
                        <option value="2" name="specialty" >Backend разработка</option>
                        <option value="1" name="specialty" >Frontend разработка</option>
                        <option value="7" name="specialty" >Project manager</option>
                        <option value="3" name="specialty" >Геймдев</option>
                          <option value="4" name="specialty" >Девопс</option>
                          <option value="5" name="specialty" >Дизайн</option>
                          <option value="6" name="specialty" >Продукт</option>
                          <option value="8" name="specialty" >Тестирование</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      <label class="mb-2 text-dark" for="vacancySalaryMin">Зарплата от</label>
                      <input class="form-control" type="text" value="{{ vacancy.salary_min }}" name="salary_min" id="vacancySalaryMin">
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      <label class="mb-2" for="vacancySalaryMax">Зарплата до</label>
                      <input class="form-control" type="text" value="{{ vacancy.salary_max }}" name="salary_max" id="vacancySalaryMax">
                    </div>
                  </div>
                </div>
                <div class="form-group pb-2">
                  <label class="mb-2 text-dark" for="vacancySkills">Требуемые навыки</label>
                  <textarea class="form-control" rows="3" id="vacancySkills" name="skills" style="color:#000;">{{ vacancy.skills }}</textarea>
                </div>
                <div class="form-group pb-2">
                  <label class="mb-2 text-dark" for="vacancyDescription">Описание вакансии</label>
                  <textarea class="form-control" rows="13" id="vacancyDescription" name="description" style="color:#000;">{{ vacancy.description }}</textarea>
                </div>
                <div class="form-group">
                  <input type="submit" class="btn btn-info" value="Сохранить">
                </div>
              </form>

              <!-- END Vacancy info -->

              <!-- Applications -->
              {% for app in application_list %}
              <h2 class="h4 pt-2 pb-3">Отклики - {{ count.count }}</h2>
              <!-- Application 1 -->

              <div class="card mt-3">
                <div class="card-body px-4">
                  <p class="mb-1 font-weight-bold">{{ app.written_username }}</p>
                  <p class="mb-2"><a href="tel:+79002842324" class="text-dark">{{ app.written_phone}}</a></p>
                  <p class="mb-1">{{ app.written_cover_letter }}</p>
                </div>
              </div>
              <!-- END Application 1 -->
              {% endfor %}
              <!-- END Applications -->
            </section>
            <!-- END Tab -->
          </div>
        </div>
      </div>
    </div>
  </main>
</form>
{% endblock %}

vacancies/templates/vacancies/vacancy-list.html
{% extends "public/base.html" %}

{% block content %}
  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link" href="{% url "my_company" %}">1. Информация о&nbsp;компании</a>
            <a class="nav-link active" href="{% url "company_vacancies" %}">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">

        <div class="card">
          <div class="card-body px-4 pb-4">
            <section class="tab-pane fade show active">
              <h2 class="h4 pt-2 pb-3">Вакансии</h2>
              <!-- vacancy state 1 -->
              {% for vacancy in vacancy_list %}
              <div class="card mt-3">
                <div class="card-body px-4">
                  <div class="row align-items-center">
                    <div class="col-6 col-lg-8">
                      <a href="{% url "update_vacancy" vacancy.id %}" class="mb-1">{{  vacancy.title }}</a>
                      <p class="mb-1">
                        <span class="mr-4">до {{ vacancy.salary_max }}</span><a class="text-info" >отклики: {{ vacancy.applications.count }} </a>
                      </p>
                    </div>
                    <div class="col-6 col-lg-4 text-right">
                      <a href="{% url "update_vacancy" vacancy.id %}" class="btn btn-outline-info">Изменить</a>
                    </div>
                  </div>
                </div>
              </div>
                {% endfor %}

              <div class="form-group pt-4">
              <a href="{% url "create_vacancy" %}" class="btn btn-info">Добавить вакансию</a>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

vacancies/templates/vacancies/vacancy.html
{% extends "public/base.html" %}


{% block content %}
        <main class="container mt-3 pb-5">
        <div class="row mt-5">
            <div class="col-12 col-lg-2">
                <div class="pl-3 mb-5">
                    <p><a href="#">Назад</a></p>
                </div>
            </div>
            <div class="col-12 col-lg-8">
                <section class="pl-3">
                    <a href="#"><img src="{{ vacancy.company.logo.url }}" width="130" height="80" alt=""></a>
                    <div class="d-flex align-items-baseline align-content-baseline">
                        <h1 class="h2 mt-4 font-weight-bold">{{ vacancy.title }}</h1>
                        <p class="m-0 pl-3">{{ vacancy.salary_min }} – {{ vacancy.salary_max }} Р</p>
                    </div>
                    <p class="mt-2">{{ vacancy.skills }}</p>
                    <p class="text-muted mb-4">{{ vacancy.company.name }} ({{ vacancy.company.employee_count }}
                        человек), {{ vacancy.company.location }} или удаленно</p>
                    <div style="line-height: 1.8;">
                        <p>{{ vacancy.company.deskription }}</p>
                        <p>{{ vacancy.description|safe }}
                        </p>
                    </div>

                    {% if user.is_authenticated %}
                    <form method="post" class="card mt-4 mb-3" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="card-body mx-3">
                            <p class="h5 mt-3 font-weight-normal">Отозваться на вакансию</p>
                            <div class="form-group">
                                <label class="mb-1 mt-2" for="userName">Вас зовут</label>
                                <input class="form-control" type="text" placeholder="" id="userName" name="written_username">
                            </div>
                            <div class="form-group">
                                <label class="mb-1" for="userPhone">Ваш телефон</label>
                                <input class="form-control" type="tel" placeholder="" id="userPhone" name="written_phone">
                            </div>
                            <div class="form-group">
                                <label class="mb-1" for="userMsg">Сопроводительное письмо</label>
                                <textarea class="form-control" rows="8" id="userMsg" name="written_cover_letter"></textarea>
                            </div>
                            <input type="submit" class="btn btn-primary mt-4 mb-2" value="Отправить отклик">
                        </div>
                    </form>
                        {% endif %}
                    </form>
                </section>
            </div>
        </div>
    </main>
{% endblock content %}